<template>
  <div id="app">
    <router-link to="/runes">Runes</router-link>
    <router-link :to="{ name: 'chat', params: { id: chatGroup }}">Chat</router-link>
    <span v-if="loggedIn" @click="logOut">{{userName}}</span> <!-- TODO: Settings & logout -->
    <router-link to="/login" v-else>Log in</router-link>
    <router-view></router-view>
  </div>
</template>

<script lang="ts">
import { createComponent, ref, computed, Ref } from "@vue/composition-api";
import { useStore, useGetters, useRouter } from "@u3u/vue-hooks";
import { Store } from "vuex";
import { RauState } from "@/store";

export default createComponent({
  setup(props, context) {
    const store: Ref<Store<RauState>> = useStore();
    const { user } = useGetters(["user"]);
    const { router, route } = useRouter();
    const chatGroup: Ref<string> = ref("broadcast");
    const loggedIn: Ref<boolean> = computed(() => user.value !== null);
    const userName: Ref<string> = computed(() => loggedIn.value ? user.value!.name : "");
    async function logOut() {
      await store.value.dispatch("logOut");
      if (route.value.matched.some(({ meta }) => meta.requiresAuth)) {
        router.push("/");
      }
    }

    return {
      chatGroup,
      loggedIn,
      logOut,
      userName,
    };
  },
});

/*export default Vue.extend({
  name: "app",
  computed: {
    chatGroup(): string {
      return this.$store.getters.currentChat;
    },
    loggedIn(): boolean {
      return this.$store.getters.loggedIn;
    },
    userName(): string {
      return this.loggedIn ? this.$store.getters.user.name : "Not logged in";
    },
  },
  methods: {
    logOut() {
      this.$store.dispatch("logOut").then(() => {
        if (this.$route.matched.some(record => record.meta.requiresAuth)) {
          this.$router.push("/");
        }
      });
    },
  },
});*/
</script>

<style>
/* Generated by Font Squirrel (http://www.fontsquirrel.com) on September 15, 2015 */
@font-face {
    font-family: "rau";
    src: url("./assets/font/rau-utf-webfont.eot");
    src: url("./assets/font/rau-utf-webfont.eot?#iefix") format("embedded-opentype"),
         url("./assets/font/rau-utf-webfont.woff2") format("woff2"),
         url("./assets/font/rau-utf-webfont.woff") format("woff"),
         url("./assets/font/rau-utf-webfont.ttf") format("truetype"),
         url("./assets/font/rau-utf-webfont.svg#rauregular") format("svg");
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: "rau";
    src: url("./assets/font/rau-utf-webfont.eot");
    src: url("./assets/font/rau-utf-webfont.eot?#iefix") format("embedded-opentype"),
         url("./assets/font/rau-utf-webfont.woff2") format("woff2"),
         url("./assets/font/rau-utf-webfont.woff") format("woff"),
         url("./assets/font/rau-utf-webfont.ttf") format("truetype"),
         url("./assets/font/rau-utf-webfont.svg#rauregular") format("svg");
    font-weight: bold;
    font-style: normal;
}

#app {
  width: 100%;
  font-family: "rau", "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
