<template>
  <div id="app">
    <nav class="nav-bar">
      <router-link to="/runes">Runes</router-link>
      <router-link :to="{ name: 'chat', params: { id: currentChat }}">Chat</router-link>
      <span v-if="loggedIn" @click="logOut">{{userName}}</span> <!-- TODO: Settings & logout -->
      <router-link to="/login" v-else>Log in</router-link>
    </nav>
    <router-view></router-view>
  </div>
</template>

<script lang="ts">
import { createComponent, computed } from "@vue/composition-api";
import { useGetters, useActions, useRouter } from "@/helpers";

export default createComponent({
  setup(props, context) {
    const {
      user,
      currentChat,
      loggedIn,
    } = useGetters("user", "currentChat", "loggedIn");
    const { router, route } = useRouter();
    const userName = computed(() => loggedIn.value ? user.value!.name : "");
    async function logOut() {
      await useActions("logOut").logOut();
      if (route.value.matched.some(({ meta }) => meta.requiresAuth)) {
        router.push("/");
      }
    }

    return {
      currentChat,
      loggedIn,
      logOut,
      userName,
    };
  },
});
</script>

<style>
/* Generated by Font Squirrel (http://www.fontsquirrel.com) on September 15, 2015 */
@font-face {
    font-family: "rau";
    src: url("./assets/font/rau-utf-webfont.eot");
    src: url("./assets/font/rau-utf-webfont.eot?#iefix") format("embedded-opentype"),
         url("./assets/font/rau-utf-webfont.woff2") format("woff2"),
         url("./assets/font/rau-utf-webfont.woff") format("woff"),
         url("./assets/font/rau-utf-webfont.ttf") format("truetype"),
         url("./assets/font/rau-utf-webfont.svg#rauregular") format("svg");
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: "rau";
    src: url("./assets/font/rau-utf-webfont.eot");
    src: url("./assets/font/rau-utf-webfont.eot?#iefix") format("embedded-opentype"),
         url("./assets/font/rau-utf-webfont.woff2") format("woff2"),
         url("./assets/font/rau-utf-webfont.woff") format("woff"),
         url("./assets/font/rau-utf-webfont.ttf") format("truetype"),
         url("./assets/font/rau-utf-webfont.svg#rauregular") format("svg");
    font-weight: bold;
    font-style: normal;
}

html, body {
  width: 100%;
  height: 100%;
  margin: 0;
  /*position: fixed;*/
}

#app {
  height: 100%;
  display: flex;
  flex-direction: column;
  font-family: "rau", "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

.nav-bar {
  align-items: center;
  background-color: #ccc;
  display: flex;
  flex: 0 0 auto;
  flex-direction: row;
  justify-content: center;
  height: 40px;
}

.nav-bar > a {
  border: 2px solid #ccc;
  color: #313030;
  flex: 0 0 auto;
  font-size: 1.4em;
  padding: 6px 15px;
  text-decoration: none;
}

.nav-bar > a.router-link-active {
  border-bottom: 2px solid #3109c0;
  color: #3109c0;
}

.nav-bar > a:hover {
  background-color: #bbb;
  border: 2px solid #bbb;
  border-bottom: 2px solid #5109c0;
}
</style>
