<template>
  <div id="app">
    <router-link to="/runes">Runes</router-link>
    <router-link to="/chat/global">Chat</router-link>
    <router-view></router-view>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "app",
});
</script>

<style>
/* Generated by Font Squirrel (http://www.fontsquirrel.com) on September 15, 2015 */

@font-face {
    font-family: "rau";
    src: url("./assets/font/rau-utf-webfont.eot");
    src: url("./assets/font/rau-utf-webfont.eot?#iefix") format("embedded-opentype"),
         url("./assets/font/rau-utf-webfont.woff2") format("woff2"),
         url("./assets/font/rau-utf-webfont.woff") format("woff"),
         url("./assets/font/rau-utf-webfont.ttf") format("truetype"),
         url("./assets/font/rau-utf-webfont.svg#rauregular") format("svg");
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: "rau";
    src: url("./assets/font/rau-utf-webfont.eot");
    src: url("./assets/font/rau-utf-webfont.eot?#iefix") format("embedded-opentype"),
         url("./assets/font/rau-utf-webfont.woff2") format("woff2"),
         url("./assets/font/rau-utf-webfont.woff") format("woff"),
         url("./assets/font/rau-utf-webfont.ttf") format("truetype"),
         url("./assets/font/rau-utf-webfont.svg#rauregular") format("svg");
    font-weight: bold;
    font-style: normal;
}

#app {
  width: 100%;
  font-family: "rau", "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
